# Vectors, matrices, simulateneous equations

This notebook demonstrates how and why matrices are useful. Readers may  wish to read the following content to familiarised themselves with the idea of matrices:

- [A gentle introduction](https://www.mathsisfun.com/algebra/matrix-index.html)
- [Complete Matrix tutorial math tutorial](https://www.maths.ed.ac.uk/~v1ranick/papers/matrices.pdf)





# Vectors 

One dimension 

In [1]:
a:list = (8,13)
b:list = (10,20)

In [2]:
a

(8, 13)

In [3]:
b

(10, 20)

## Let's manipulate those vectors

### Sum and substraction

In [4]:
a

(8, 13)

In [5]:
b

(10, 20)

In [6]:
c = (a[0] + b[0], a[1] + b[1])
c

(18, 33)

In [7]:
c = (a[0] - b[0], a[1] - b[1])
c

(-2, -7)

### Multiplication


In [8]:
a

(8, 13)

In [9]:

c = (5 * a[0], 5 * a[1])
c


(40, 65)

### Dot product

$a = (a_1,a_2,a_n)$
$b = (b_1,b_2,b_n)$

$a . b = (a_1 * b_2) + (a_2 * b_2) + (a_n * b_n)$

In [10]:
a

(8, 13)

In [11]:
b

(10, 20)

Let's show each step of the dot product

In [12]:
(a[0] * b[0])

80

In [13]:
(a[1] * b[1])

260

In [14]:
dot_product = (a[0] * b[0]) + (a[1] * b[1])
dot_product 

340

# Matrices

Two dimensions

In [15]:
import numpy as np
A = np.array([[20, 50], [40, 60]])
B = np.array([[9, 3], [3, 6]])

In [16]:
A

array([[20, 50],
       [40, 60]])

In [17]:
B

array([[9, 3],
       [3, 6]])

### Sum and substraction

In [18]:
np.array([[A[0][0] + B[0][0],A[0][1] + B[0][1]],
 [A[1][0] + B[1][0],A[1][1] + B[1][1]]])

array([[29, 53],
       [43, 66]])

In [19]:
np.array([[A[0][0] - B[0][0],A[0][1] - B[0][1]],
 [A[1][0] - B[1][0],A[1][1] - B[1][1]]])

array([[11, 47],
       [37, 54]])

## Multiplication

Let's apply a series of dot products

In [20]:
A

array([[20, 50],
       [40, 60]])

In [21]:
B

array([[9, 3],
       [3, 6]])

### Dot product of row 0 and column 0

Matrix A  Row 0 

In [22]:
row_0 = A[0]
row_0

array([20, 50])

Matrix B Column 0 is 

In [23]:
col_0 = np.array([B[0,0], B[1,0]])
col_0

array([9, 3])

In [24]:
dot_product = (row_0[0] * col_0[0]) + (row_0[1] * col_0[1])
dot_product 

330

### Dot product of row 0 and column 1

Matrix A  Row 0 

In [25]:
row_0 = A[0]
row_0

array([20, 50])

Matrix B Column 1 is 

In [26]:
col_1 = np.array([B[0,1], B[1,1]])
col_1

array([3, 6])

In [27]:
dot_product = (row_0[0] * col_1[0]) + (row_0[1] * col_1[1])
dot_product 

360

### Dot product of row 1 and column 0

Matrix A  Row 1 

In [28]:
row_1 = A[1]
row_1

array([40, 60])

Matrix B Column 0 is 

In [29]:
col_0 = np.array([B[0,0], B[1,0]])
col_0

array([9, 3])

In [30]:
dot_product = (row_1[0] * col_0[0]) + (row_1[1] * col_0[1])
dot_product 

540

### Dot product of row 1 and column 1

Matrix A  Row 1 

In [31]:
row_1 = A[1]
row_1

array([40, 60])

Matrix B Column 1 is 

In [32]:
col_1 = np.array([B[0,1], B[1,1]])
col_1

array([3, 6])

In [33]:
dot_product = (row_1[0] * col_1[0]) + (row_1[1] * col_1[1])
dot_product 

480

### Matrix multiplication

In [34]:
np.dot(A, B)

array([[330, 360],
       [540, 480]])

## Inverse and Identify matrix 


In [35]:
I = np.array([[1,0],[0,1]])
I

array([[1, 0],
       [0, 1]])

$inverse = \frac{1}{ad-bc}\begin{bmatrix}
d & -b\\ 
 -c & a
\end{bmatrix}$

In [36]:
A

array([[20, 50],
       [40, 60]])

Step 0 : calculate the scalar value

In [37]:
ad = (A[0,0] * A[1,1])
ad

1200

In [38]:
bc = (A[0,1] * A[1,0])
bc 

2000

In [39]:
ad-bc

-800

In [40]:
scalar = 1/(ad-bc)
scalar

-0.00125

In [41]:
row_0 = [A[1,1],-A[0,1]]
row_1 = [-A[1,0],A[0,0]]

In [42]:
prep_A = np.array([row_0, row_1])
prep_A

array([[ 60, -50],
       [-40,  20]])

In [43]:
inverse = scalar * prep_A
inverse

array([[-0.075 ,  0.0625],
       [ 0.05  , -0.025 ]])

In [44]:
np.linalg.inv(A)

array([[-0.075 ,  0.0625],
       [ 0.05  , -0.025 ]])

Assume  the very low values are 0s. 

In [64]:
np.dot(A, inverse)

array([[ 1.00000000e+00,  6.93889390e-17,  1.73472348e-18,
         5.55111512e-17],
       [ 1.22251035e-17,  1.00000000e+00,  1.27393681e-18,
        -4.51501635e-17],
       [ 8.32667268e-17,  1.38777878e-16,  1.00000000e+00,
        -1.11022302e-16],
       [-4.16333634e-17,  4.16333634e-17, -8.67361738e-18,
         1.00000000e+00]])

# Solving simulateneous equations

## A small and simple example

[Some more info](https://www.mathcentre.ac.uk/resources/uploaded/sigma-matrices8-2009-1.pdf)

Let's imagine we have a system of equations: 

$20x + 50y = 8$

$40x + 60y = 13$

In [46]:
A

array([[20, 50],
       [40, 60]])

In [47]:
B = a
B

(8, 13)

inverse of A

In [48]:
inverse 

array([[-0.075 ,  0.0625],
       [ 0.05  , -0.025 ]])

$X = A^{-1}B$

In [49]:
X = np.dot(inverse, B)
X

array([0.2125, 0.075 ])

Let's verify the values of x and y

In [50]:
A[0,0] * X[0] + A[0,1] * X[1]

8.0

In [51]:
A[1,0] * X[0] + A[1,1] * X[1]

13.0

In [52]:
B

(8, 13)

## A more complex example

$ x_1 + 2.5 x_2 + 10 x_3 + 5 x_4 = 150$

$ 0.5x_1 + 20 x_2 + 1.2 x_3 + 0.45 x_4 = 200$

$ 23 x_1 + 10 x_2 +  34 x_4 = 1000$

$  9 x_2 + 5.2 x_3 + 4 x_3 + 7 x_4 = 200$

It becomes

$AX = B$




In [53]:
A = np.array([[1,2.5,10,5],
              [0.5, 20, 1.2, 0.45],
              [23,10,0,34],
              [0, 9, 5.2,7]])
A

array([[ 1.  ,  2.5 , 10.  ,  5.  ],
       [ 0.5 , 20.  ,  1.2 ,  0.45],
       [23.  , 10.  ,  0.  , 34.  ],
       [ 0.  ,  9.  ,  5.2 ,  7.  ]])

In [54]:
B = [150, 200, 1000,200]

In [55]:
inverse = np.linalg.inv(A)
inverse

array([[ 0.13170231,  0.08882382,  0.03582112, -0.27377148],
       [-0.00928939,  0.04848198, -0.00065007,  0.00667606],
       [ 0.1323324 ,  0.01617018, -0.00610511, -0.06590927],
       [-0.08636057, -0.07434611,  0.00537103,  0.18323481]])

$X = A^{-1}B$

In [56]:
X = np.dot(inverse, B)
X

array([18.58693458,  8.98813032,  3.79693276, 14.1946824 ])

Let's verify the values of x and y

In [57]:
A[0,0] * X[0] + A[0,1] * X[1] + A[0,2] * X[2] + A[0,3] * X[3]

150.0

In [58]:
A[1,0] * X[0] + A[1,1] * X[1] + A[1,2] * X[2] + A[1,3] * X[3]

199.99999999999994

In [59]:
A[2,0] * X[0] + A[2,1] * X[1] + A[2,2] * X[2] + A[2,3] * X[3]

999.9999999999997

In [60]:
A[3,0] * X[0] + A[3,1] * X[1] + A[3,2] * X[2] + A[3,3] * X[3]

199.99999999999997

In [61]:
B

[150, 200, 1000, 200]